### ISSUE TITLE
Publish GSoC Talk

### ISSUE THREAD

**Issue by ApolloZhu** [UWAppDev/roadmap#3]
- [x] Fix transcript
- [x] Enable studio effect
- [x] Editing
- [x] Export to Google Drive for archive
- [x] Release on YouTube
- [x] Release on bilibili?

**Comment by ApolloZhu** [comment]
Blocked by https://github.com/UWAppDev/Board/issues/16

**Comment by XinyiXiang** [comment]
Now public at https://youtu.be/iU6KSGXxkek.

Would @ApolloZhu share insights on bilibili publishing or take the task over?

**Comment by XinyiXiang** [comment]
Available on YouTube and Bilibili
